### ISSUE TITLE
请问和 osquery 相比，有哪些优势吗？

### ISSUE THREAD

**Issue by yimingsir** [EBWi11/AgentSmith-HIDS#17]

**Comment by EBWi11** [comment]
AgentSmith-HIDS和osquery相比是完全不同定位的两种工具，如果非要在**入侵检测**领域上进行比较的话，那么AgentSmith-HIDS具有内核驱动模块，可以支持实时的**execve/connect/create_file/load_lkm_module/DNS query/Process Inject/Cred Change**数据捕获和传递，还具备4中rootkit检测能力，并且天然支持容器，且由于是在ring0层的进行的数据捕获，具有天然难以被绕过的特性，这些应该都是相对于osquery的优点，并且理论上osquery可以得到的数据AgentSmith-HIDS都可以，因为我们也有用户态模块，可以自己编写模块进行支持，如现在已有的**RPMList/ListeningSockets/SystemUser/CrontabList**这些是我已经加的用户态自定义模块。如果你对osquery比较了解，那么应该明白很多AgentSmith-HIDS的核心能力是它无法做到的。

**Comment by yimingsir** [comment]
非常感谢您的解答
