### ISSUE TITLE
kretprobe 回调函数

### ISSUE THREAD

**Issue by VistaAsteria** [EBWi11/AgentSmith-HIDS#22]
kretprobe是跟踪流，有阻断功能吗，可通过返回值来实现吗？

**Comment by EBWi11** [comment]
目前还没有考虑阻断，定位是IDS不是IPS，没有深入研究过，但是我理解应该是不能通过返回值来实现阻断的。但是可以通过`send_sig_info(SIGKILL, SEND_SIG_PRIV, p_task);`来实现kill相关进程

**Comment by VistaAsteria** [comment]
> 
> 
> 目前还没有考虑阻断，定位是IDS不是IPS，没有深入研究过，但是我理解应该是不能通过返回值来实现阻断的。但是可以通过`send_sig_info(SIGKILL, SEND_SIG_PRIV, p_task);`来实现kill相关进程

好的，谢谢！
